---
- name: loop play
  hosts: localhost
  gather_facts: no
  roles:
    - roles/loop-test-role

- name: template play
  hosts: localhost
  gather_facts: no
  vars_files: vars.yml
  roles:
    - roles/template-test-role
  tags: temp-tag
